app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify, session, current_app
from flask_login import login_user, logout_user, login_required, current_user
from app.models import User, Cloth
from app import db, google, s3, image_processing_service_url, profileImageS3Bucket, login_manager
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from uuid import uuid4
from .utils import upload_profile_image, send_images_to_process, generate_presigned_url, allowed_file, remove_background_from_image, upload_profile_image_bytes
import traceback
import os, requests, uuid

routes = Blueprint('routes', __name__)

@routes.route('/get-google-client-id', methods=['GET'])
def get_google_client_id():
    """
    Flask route to return the Google Client ID from the server configuration.
    """
    google_client_id = current_app.config['GOOGLE_CLIENT_ID']
    return jsonify({"google_client_id": google_client_id})

@routes.route('/verify-token', methods=['POST'])
def verify_google_token():
    try:
        print('verify_google_token')
        # Get the token from the frontend
        token = request.json.get('token')

        # Verify the token with Google's OAuth2 API
        url = f"https://oauth2.googleapis.com/tokeninfo?id_token={token}"
        response = requests.get(url)

        if response.status_code != 200:
            return jsonify({"success": False, "message": "Failed to verify token"}), 400

        # Parse the response from Google
        profile = response.json()

        # Get email from the profile
        email = profile['email']
        name = profile.get('name', '')

        # Check if the user exists in the database
        user = User.query.filter_by(email=email).first()

        if not user:
            # Create a new user if they don't exist
            user_id = str(uuid4())  # Generate unique UUID
            user = User(id=user_id, name=name, email=email, password=None)  # No password for Google OAuth users
            db.session.add(user)
            db.session.commit()

        # Log in the user
        login_user(user)

        # Send a success response with the redirect URL
        return jsonify({"success": True, "message": "Logged in successfully", "redirect_url": url_for('routes.show_clothes')})

    except Exception as e:
        print(f"Error verifying Google token: {e}")
        return jsonify({"success": False, "message": "Error verifying token"}), 500


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Get JSON data
        data = request.get_json()
        email = data.get('email')
        password = data.get('password')
        user = User.query.filter_by(email=email).first()

        if not user:
            return jsonify({'message': 'The email you entered does not exist in our system.', 'success': False})

        if not user.check_password(password):
            return jsonify({'message': 'Invalid password', 'success': False}), 401

        # Create a unique session ID using UUID4
        session_id = str(uuid4())
        session['user_id'] = session_id
        user.session_id = session_id
        db.session.commit()

        # Log in the user
        login_user(user)

        return jsonify({'message': 'Logged in successfully', 'success': True, 'redirect_url': url_for('routes.show_clothes')})

    return render_template('login.html')

@routes.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        # Get JSON data
        data = request.get_json()
        name = data.get('username')
        email = data.get('email')
        password = data.get('password')

        # Check if email already exists
        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            return jsonify({'message': 'An account with that email already exists.', 'success': False}), 400

        # Create new user
        user_id = str(uuid4())  # Generate unique user ID
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
        new_user = User(id=user_id, name=name, email=email, password=hashed_password)

        # Add user to the database
        db.session.add(new_user)
        db.session.commit()

        # Log in the user
        login_user(new_user)

        return jsonify({'message': 'Account created successfully', 'success': True})

    return render_template('signup.html')

@routes.route('/process_images', methods=['POST'])
@login_required
def process_images():
    data = request.json
    user_id = current_user.id
    profile_image_url = generate_presigned_url(current_user.profile_picture)
    cloth_image_link = data['cloth_image_link']
    cloth_id = data['cloth_id']

    final_image_url = send_images_to_process(user_id, cloth_id, image_processing_service_url, profile_image_url, cloth_image_link)

    if final_image_url:
        return jsonify({"status": "success", "final_image_url": final_image_url}), 200
    else:
        return jsonify({"status": "error", "message": "Failed to process the images."}), 500

@routes.route('/google_login')
def google_login():
    print('in google login')
    redirect_uri = url_for('routes.google_authorize', _external=True)
    return google.authorize_redirect(redirect_uri)

@routes.route('/google_authorize')
def google_authorize():
    # Exchange the authorization code for a token
    token = google.authorize_access_token()
    
    # Fetch user information from Google's userinfo endpoint
    resp = google.get('https://www.googleapis.com/oauth2/v3/userinfo')  # Use full URL
    
    # Parse the response
    user_info = resp.json()

    # Handle the user info and log in the user
    email = user_info['email']
    name = user_info.get('name', '')

    # Check if user exists in the database
    user = User.query.filter_by(email=email).first()

    if not user:
        # Create a new user if they don't exist
        user_id = str(uuid4())  # Generate unique UUID
        user = User(id=user_id, name=name, email=email, password=None)  # No password for OAuth users
        db.session.add(user)
        db.session.commit()

    # Log the user in
    login_user(user)

    return redirect(url_for('routes.show_clothes'))



@routes.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('routes.index'))

@routes.route('/')
def index():
    hasUploadedProfileImage = None
    if current_user.is_authenticated:
        hasUploadedProfileImage = current_user.profile_picture

    return render_template('index2.html', is_authenticated=current_user.is_authenticated, user=current_user, hasUploadedProfileImage=hasUploadedProfileImage)

@routes.route('/upload_portrait', methods=['POST'])
@login_required
def upload_portrait():
    try:
        print('upload_portrait')
        portrait_file = request.files.get('profile-image')
        if not portrait_file or not allowed_file(portrait_file.filename):
            return jsonify({"error": "Invalid or no file selected"}), 400

        output_io = remove_background_from_image(portrait_file)
        print('Secure and make filename unique')
        # Secure and make filename unique
        filename = secure_filename(f"{current_user.id}_{uuid.uuid4().hex}_{portrait_file.filename}")

        print('upload_profile_image')
        # Upload the portrait file to S3
        #upload_profile_image(portrait_file, filename)
        upload_profile_image_bytes(output_io, filename)

        # Store the file key in the database
        current_user.profile_picture = filename
        db.session.commit()

        print('Generate a pre-signed URL for the uploaded image')
        # Generate a pre-signed URL for the uploaded image
        presigned_url = generate_presigned_url(filename)

        return jsonify({"message": "Profile image uploaded successfully", "image_url": presigned_url}), 200

    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@routes.route('/get-presigned-url', methods=['GET'])
@login_required
def get_profile_image_presigned_url():
    print('get_profile_image_presigned_url')
    try:
        s3_key = current_user.profile_picture
        if not s3_key:
            return jsonify({"error": "No profile picture uploaded"}), 400

        presigned_url = generate_presigned_url(s3_key)
        if presigned_url:
            return jsonify(success=True, presigned_url=presigned_url)
        else:
            return jsonify(success=False, message="Failed to generate pre-signed URL"), 500

    except Exception as e:
        return jsonify(success=False, message=str(e)), 500

@routes.route('/clothes')
def show_clothes():
    # Query the Cloth table to retrieve all clothes
    clothes = Cloth.query.all()

    # Prepare the data to be passed to the template
    clothes_data = []
    for cloth in clothes:
        images = cloth.Images.split(',')
        try_on_link = images[0] if images else None  # Use the first image as the TryOnLink

        clothes_data.append({
            'ClothesID': cloth.id,
            'ProductName': cloth.ProductName,
            'Brand': cloth.Brand,
            'Price': cloth.Price,
            'Images': cloth.Images.split(','),
            'Sizes': cloth.Sizes,
            'Description': cloth.Description,
            'TryOnLink': try_on_link
        })

    return render_template('index2.html', clothes=clothes_data)

app/templates/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fashion Assistant</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</head>
<body>
<div class="navbar">
  <a href="{{ url_for('routes.index') }}" class="logo">
    <img src="{{ url_for('static', filename='images/logo.png') }}">
  </a>
  <!-- Add more links for other pages -->
  <div class="user-info">
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('routes.logout') }}">Logout</a>
    {% else %}
    <a href="#" class="login-link">Login</a>
    <a href="#" class="signup-link">Sign Up</a>
    {% endif %}
  </div>
</div>

<!--<h1 class="hero-title">Your Personal Fashion Assistant Pro: AI-Powered Style Guidance & Inspiration</h1>-->
<p class="tagline">Discover your ultimate fashion potential with our cutting-edge AI stylist, providing personalized recommendations and trend insights.</p>
<a href="#" class="chat-button">Let's Chat Now</a>

<div id="login-modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Login</h2>
    <form id="login-form">
      <label for="login-email">Email:</label>
      <input type="email" id="login-email" name="login-email" required>
      <br>
      <label for="login-password">Password:</label>
      <input type="password" id="login-password" name="login-password" required>
      <br>
      <button type="submit">Login</button>
    </form>
    <p id="login-error-message"></p>
  </div>
</div>

<div class="modal" id="signup-modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Sign up</h2>
    <form id="signup-form">
      <label for="signup-username">Username:</label>
      <input type="username" id="signup-username" name="signup-username" required>
      <br>
      <label for="signup-email">Email:</label>
      <input type="email" id="signup-email" name="signup-email" required>
      <br>
      <label for="signup-password">Password:</label>
      <input type="password" id="signup-password" name="signup-password" required>
      <br>
      <button type="submit">Sign up</button>
    </form>

    <h3>Sign up with Google</h3>
    <button id="google-signup-btn">
      <i class="fab fa-google"></i> Sign up with Google
    </button>

  </div>
</div>

{% if current_user.is_authenticated %}
<div class="chat-box">
  <div id="chat-messages" style="height: 80%; overflow-y: auto; padding: 5px;"></div>
  <form id="chat-form" style="display: flex;">
    <input id="chat-input" type="text" style="flex-grow: 1;" placeholder="Please ask me anything about clothes shopping and fashion trends ...">
    <button type="submit" style="width: 20%;">Send</button>
  </form>
</div>
{% endif %}

<div class="search-results">
  {% for result in search_results %}
  <div class="search-result">
    <img src="{{ result.image_url }}" alt="{{ result.title }}" width="100%">
    <a href="{{ result.link }}" target="_blank">{{ result.title }}</a>
  </div>
  {% endfor %}
</div>

</body>

<script>
  var signupUrl = "{{ url_for('routes.signup') }}";
  var indexUrl = "{{ url_for('routes.index') }}";
  var loginUrl = "{{ url_for('routes.login') }}";
  var isUserAuthenticated = {{ is_authenticated|lower }};
</script>

</html>

app/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WardrobeVue</title>

    <script src="https://accounts.google.com/gsi/client" async defer></script>

    <!-- Cropper CSS and JS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.11/cropper.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.11/cropper.min.js"></script>

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- jQuery library (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper.js (used for popovers and tooltips in Bootstrap 4) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Include lazysizes from a CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.3.0/lazysizes.min.js" async></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</head>
<body>
<div class="navbar">
  <a href="{{ url_for('routes.index') }}" >
    <img src="{{ url_for('static', filename='images/logo.png') }}" class="logo" alt="WardrobeVue Logo" title="WardrobeVue">
  </a>
  <!-- Add more links for other pages -->
  <div class="user-info">
    {% if current_user.is_authenticated %}
      <a href="#" class="profile-link">Profile</a>
      <a href="{{ url_for('routes.logout') }}">Logout</a>
    {% else %}
      <a href="#" class="login-link">Login</a>
      <a href="#" class="signup-link">Sign Up</a>
    {% endif %}
  </div>
</div>

<div class="container">
    <!-- Other content goes here -->
    <img id="websiteImage" src="{{ url_for('static', filename='images/background_image.png') }}" alt="Website Image">


    <!--<h1 class="hero-title">Your Personal Fashion Assistant Pro: AI-Powered Style Guidance & Inspiration</h1>-->
    <p class="tagline">Try on the high fashion products from 500+ trusted stores.</p>
    <input type="file" name="profile-image" id="portrait-file" accept="image/*" class="hidden">
    <label for="portrait-file" class="upload-portrait-btn">Upload Full Body Portrait</label>

    <!-- Login Modal -->
    <div id="login-modal" class="modal">
        <div class="user-modal-content">
            <span class="close">&times;</span>
            <h2>Login</h2>
            <form id="login-form">
                <label for="login-email">Email:</label>
                <input type="email" id="login-email" name="login-email" required>
                <br>
                <label for="login-password">Password:</label>
                <input type="password" id="login-password" name="login-password" required>
                <br>
                <button type="submit">Login</button>
            </form>
            <p id="login-error-message"></p>

            <!-- Divider for alternative login methods -->
            <hr>


            <!-- Google Login Button -->
            <button id="google-login-button" class="google-login-btn">
                <img src="{{ url_for('static', filename='images/web_light_rd_na@2x.png') }}" alt="Google Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                Login with Google
            </button>
        </div>
    </div>

    <!-- Signup Modal -->
    <div id="signup-modal" class="modal">
        <div class="user-modal-content">
            <span class="close">&times;</span>
            <h2>Sign Up</h2>

            <form id="signup-form">
                <label for="signup-username">Username:</label>
                <input type="text" id="signup-username" name="signup-username" required>
                <br>
                <label for="signup-email">Email:</label>
                <input type="email" id="signup-email" name="signup-email" required>
                <br>
                <label for="signup-password">Password:</label>
                <input type="password" id="signup-password" name="signup-password" required>
                <br>
                <button type="submit">Sign Up</button>
            </form>
            <p id="signup-error-message"></p>

            <!-- Divider for alternative signup methods -->
            <hr>

            <!-- Google Sign Up Button -->
            <button id="google-signup-btn" class="google-login-btn">
                <img src="{{ url_for('static', filename='images/web_light_rd_na@2x.png') }}" alt="Google Icon" style="width: 20px; height: 20px; vertical-align: middle;">
                Sign up with Google
            </button>
        </div>
    </div>



    <div class="modal" id="profile-modal">
        <div class="modal-content">
            <span class="close">&times;</span>

            {% if current_user.is_authenticated %}
            <!-- Displayed profile image -->
            <img id="profile_image_url" src="{{ profile_image_url }}" alt="Profile Picture">
            {% endif %}

            <!-- Profile update form -->
            <form action={{ url_for('routes.upload_portrait') }} id="profile-form" enctype="multipart/form-data">
                <label for="profile-image">Update Profile Image:</label>
                <input type="file" id="profile-image" name="profile-image" accept="image/*" onchange="previewImage(event)">
                <button type="submit">Update Profile</button>
            </form>

            <p id="profile-error-message"></p>
        </div>
    </div>

    <div class="popup-overlay">
        <div class="popup-content">
            <img id="processed-image" src="" alt="Processed Image">
            <button class="close-button" onclick="this.parentElement.parentElement.style.display='none';">Close</button>
        </div>
    </div>

    <div class="clothes-grid">

        {% for cloth in clothes %}
        <div class="clothes-item carousel slide" data-ride="carousel" data-interval="2000" id="carousel{{ loop.index }}">
            <div class="carousel-inner">
                {% for image_url in cloth['Images'] %}
                <div class="carousel-item {% if loop.first %}active{% endif %}">
                    <img src="{{ image_url }}" alt="Clothes {{ loop.index }} Image {{ loop.index }}" class="d-block w-100">
                </div>
                {% endfor %}
            </div>
            <a href="#" class="tryon-hover-bar" data-clothes-id="{{ cloth['ClothesID'] }}" data-clothes-link="{{ cloth['TryOnLink'] }}">Try On</a>
        </div>
        {% endfor %}

    </div>

    <!-- Loading Bar (initially hidden) -->
    <!--<div class="loading-bar" style="display: none;">
        <div class="progress"></div>
    </div>-->

    <div id="spinner" class="spinner"></div>


    <!-- Popup (initially hidden) -->
    <div class="processed-image-popup" style="display: none;">
        <img src="" alt="Processed Image" id="processed-image">
        <button id="close-popup">Close</button>
    </div>

    <div id="feedback" style="display: none; color: red;"></div>





    <!--{% if current_user.is_authenticated %}-->
    <!--<div class="chat-box">-->
    <!--  <div id="chat-messages" style="height: 80%; overflow-y: auto; padding: 5px;"></div>-->
    <!--  <form id="chat-form" style="display: flex;">-->
    <!--    <input id="chat-input" type="text" style="flex-grow: 1;" placeholder="Please ask me anything about clothes shopping and fashion trends ...">-->
    <!--    <button type="submit" style="width: 20%;">Send</button>-->
    <!--  </form>-->
    <!--</div>-->
    <!--{% endif %}-->
    <!--<div class="search-results">-->
    <!--  {% for result in search_results %}-->
    <!--  <div class="search-result">-->
    <!--    <img src="{{ result.image_url }}" alt="{{ result.title }}" width="100%">-->
    <!--    <a href="{{ result.link }}" target="_blank">{{ result.title }}</a>-->
    <!--  </div>-->
    <!--  {% endfor %}-->
    <!--</div>-->
</div>
</body>

<script>
  var signupUrl = "{{ url_for('routes.signup') }}";
  var indexUrl = "{{ url_for('routes.index') }}";
  var loginUrl = "{{ url_for('routes.login') }}";
  var fileUploadUrl = "{{ url_for('routes.upload_portrait') }}";
  var isUserAuthenticated = "{{ is_authenticated| lower }}"; 
  var profileImageUrl = "{{ profile_image_url }}";
  var hasUploadedProfileImage = "{{ hasUploadedProfileImage|lower }}";
  var imageProcessUrl = "{{ url_for('routes.process_images')  }}"
  var googleClientId = "{{ google_client_id }}"; // Passed from Flask
</script>

</html>

app/templates/login.html
{% extends 'index2.html' %}

{% block login %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
<div class="modal" id="login-modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Login</h2>
    <form id="login-form">
      <label for="login-email">Email:</label>
      <input type="email" id="login-email" name="login-email" required>
      <br>
      <label for="login-password">Password:</label>
      <input type="password" id="login-password" name="login-password" required>
      <br>
      <button type="submit">Login</button>
    </form>
    <p id="login-error-message"></p>
  </div>
</div>


{% endblock %}

app/templates/profile.html
{% extends 'index2.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

<div class="container">
    <h1>Welcome, {{ current_user.username }}</h1>
    <p>Email: {{ current_user.email }}</p>

    <img src="{{ current_user.profile_picture }}" alt="Profile Picture" id="uploadedImage">
    <form action="{{ url_for('routes.upload_portrait') }}" method="post" enctype="multipart/form-data">
        <label for="portrait">Update Profile Image:</label>
        <input type="file" id="portrait" name="portrait" accept=".jpg, .jpeg, .png">
        <button type="submit">Upload</button>
    </form>

    <div id="controls">
        <button type="button" onclick="zoomIn()">Zoom In</button>
        <button type="button" onclick="zoomOut()">Zoom Out</button>
    </div>
</div>

<script>
  var signupUrl = "{{ url_for('routes.signup') }}";
  var indexUrl = "{{ url_for('routes.index') }}";
  var loginUrl = "{{ url_for('routes.login') }}";
  var fileUploadUrl = "{{ url_for('routes.upload_portrait') }}";
  var isUserAuthenticated = "{{ is_authenticated|lower }}";

  const uploadedImage = document.getElementById('uploadedImage');
  let scale = 1;

  function zoomIn() {
      scale += 0.1;
      uploadedImage.style.transform = `scale(${scale})`;
  }

  function zoomOut() {
      scale = Math.max(0.1, scale - 0.1);
      uploadedImage.style.transform = `scale(${scale})`;
  }
</script>
{% endblock %}

app/templates/signup.html
{% extends 'index2.html' %}

{% block signup %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
<div class="modal" id="signup-modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Sign up</h2>
    <form id="signup-form">
      <label for="signup-username">Username:</label>
      <input type="username" id="signup-username" name="signup-username" required>
      <br>
      <label for="signup-email">Email:</label>
      <input type="email" id="signup-email" name="signup-email" required>
      <br>
      <label for="signup-password">Password:</label>
      <input type="password" id="signup-password" name="signup-password" required>
      <br>
      <button type="submit">Sign up</button>
    </form>

    <h3>Sign up with Google</h3>
    <button id="google-signup-btn">
      <i class="fab fa-google"></i> Sign up with Google
    </button>

  </div>
</div>

<script src="{{ url_for('static', filename='js/google-signup.js') }}"></script>
{% endblock %}